basePath: /
definitions:
  api.Err:
    properties:
      error:
        type: string
    type: object
  api.HelloResponse:
    properties:
      message:
        type: string
    type: object
  api.countriesListResponse:
    properties:
      countries:
        items:
          $ref: '#/definitions/models.Country'
        type: array
      currentIndex:
        type: integer
      itemInASinglePage:
        type: integer
      totalCountry:
        type: integer
      totalPageList:
        items:
          type: integer
        type: array
    type: object
  api.createAccountRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.createAccountResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  api.loginRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.loginResponse:
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: string
      refreshToken:
        type: string
      refreshTokenExpiresAt:
        type: string
      session_id:
        type: string
      user:
        $ref: '#/definitions/api.createAccountResponse'
    type: object
  api.renewAccessTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  api.renewAccessTokenResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
    type: object
  api.stateListResponse:
    properties:
      currentIndex:
        type: integer
      itemInASinglePage:
        type: integer
      states:
        items:
          $ref: '#/definitions/models.State'
        type: array
      totalPageList:
        items:
          type: integer
        type: array
      totalState:
        type: integer
    type: object
  api.stateListResponseByCountry:
    properties:
      states:
        items:
          $ref: '#/definitions/models.State'
        type: array
    type: object
  api.successResponse:
    properties:
      message:
        type: string
    type: object
  models.Country:
    properties:
      countryShortName:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.State:
    properties:
      countryId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      stateName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Country API
  version: "1.0"
paths:
  /country/add:
    get:
      consumes:
      - application/json
      operationId: getCountryByAPI
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: Save country data to database by fetching from third party api
      tags:
      - Country
  /country/list/{page}:
    get:
      consumes:
      - application/json
      operationId: getCountriesList
      parameters:
      - description: page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.countriesListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: get countries list
      tags:
      - Country
  /hello:
    get:
      operationId: Hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HelloResponse'
      summary: print hello world
      tags:
      - Hello
  /state/add:
    get:
      consumes:
      - application/json
      operationId: getStateByAPI
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: Save state data to database by fetching from third party api
      tags:
      - State
  /state/country-state/{country}:
    get:
      consumes:
      - application/json
      operationId: StateByCountry
      parameters:
      - description: country name
        in: path
        name: country
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.stateListResponseByCountry'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: Get states by the country name
      tags:
      - State
  /state/list/{page}:
    get:
      consumes:
      - application/json
      operationId: getStatesList
      parameters:
      - description: page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.stateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: get states list
      tags:
      - State
  /user/create:
    post:
      consumes:
      - application/json
      operationId: CreateUser
      parameters:
      - description: create user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.createAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.createAccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: add a new user
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      operationId: Login
      parameters:
      - description: Login request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: login and generate token with JWT
      tags:
      - User
  /user/renew-access-token:
    post:
      consumes:
      - application/json
      operationId: Renew Token
      parameters:
      - description: renew access token by refresh token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.renewAccessTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.renewAccessTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Err'
      summary: renew token
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
